### ISSUE TITLE
Error when trying to run all tests of file

### ISSUE THREAD

**Issue by otavioschwanck** [weizheheng/ror.nvim#4]
Running with: `lua require('ror.test').run()`:

^I[C]: in function 'nvim_buf_set_extmark'
^I...m/site/pack/packer/start/ror.nvim/lua/ror/test/rspec.lua:61: in function <...m/site/pack/packer/start/ror.nvim/lua/ror/test/rspec.lua:8>

**Comment by weizheheng** [comment]
Hi, thanks for the issue. I couldn't reproduce the issue myself, do you mind sharing the full error messages?

Also, are you on the latest main branch? If not you can try updating and see if the problem still persists.

**Comment by otavioschwanck** [comment]
Upgrading it fix it.
