### ISSUE TITLE
Auto attach when pry, debugger or byebug is detected

### ISSUE THREAD

**Issue by otavioschwanck** [weizheheng/ror.nvim#5]
Would be awesome to have it

**Comment by weizheheng** [comment]
This is great feedback, I actually wanted this behaviour myself as well. However, I haven't figured out how to tell if a debugger is present.

**Comment by otavioschwanck** [comment]
1. You can check the last line of terminal buffer, if contains those words, it opens.  Maybe i can try to do in the weekend.
