### ISSUE TITLE
Feature Request:  Notification when tests run is complete.

### ISSUE THREAD

**Issue by otavioschwanck** [weizheheng/ror.nvim#6]
When all tests pass:

All tests passed

When some tests fails:

3 tests of 12 failed.

**Comment by weizheheng** [comment]
Thank you for your interest in this plugin. 

I have added some basic support for this as shown in this image.
<img width="543" alt="CleanShot 2022-11-12 at 21 42 52@2x" src="https://user-images.githubusercontent.com/40255418/201476988-6a3a52af-a9e3-43da-86ce-cca5c59886bb.png">

Not working on your other issues, but I have been playing around with coverage. Now you can do something like

<img width="858" alt="CleanShot 2022-11-12 at 21 45 19@2x" src="https://user-images.githubusercontent.com/40255418/201477028-9fc36e16-deab-41ed-a3f4-8cfe438f6873.png">

**Comment by otavioschwanck** [comment]
> Thank you for your interest in this plugin.
> 
> I have added some basic support for this as shown in this image. <img alt="CleanShot 2022-11-12 at 21 42 52@2x" width="543" src="https://user-images.githubusercontent.com/40255418/201476988-6a3a52af-a9e3-43da-86ce-cca5c59886bb.png">
> 
> Not working on your other issues, but I have been playing around with coverage. Now you can do something like
> 
> <img alt="CleanShot 2022-11-12 at 21 45 19@2x" width="858" src="https://user-images.githubusercontent.com/40255418/201477028-9fc36e16-deab-41ed-a3f4-8cfe438f6873.png">

Awesome.  About the other issues, i can work on that.
